#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -o errexit
set -o nounset
set -o errtrace
set -o pipefail

source /usr/libexec/helper-scripts/package_installed_check.bsh

keyrings_dir='/etc/apt/keyrings'
key_file="${keyrings_dir}/packages.mozilla.org.asc"
remote_signing_key='https://packages.mozilla.org/apt/repo-signing-key.gpg'
key_fingerprint='35BAA0B33E9EB396F59CA838C0BA5CE6DC6315A3'
apt_source_line='deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] tor+https://packages.mozilla.org/apt mozilla main'
apt_source_file='/etc/apt/sources.list.d/mozilla.list'
mozilla_repo_pin='Package: *
Pin: origin packages.mozilla.org
Pin-Priority: 1000'
mozilla_repo_pin_file='/etc/apt/preferences.d/mozilla'
mozilla_maintainer_line='Maintainer: Mozilla <release@mozilla.com>'

temp_dir="$(mktemp -d)"
temp_key_file="${temp_dir}/mozilla-keyfile"
modify_mode="${1:-install}"

exit_function() {
  safe-rm -rf -- "${temp_dir}"
}

trap 'exit_function' EXIT

case "${modify_mode}" in
  install)
    mkdir --parents -- "${keyrings_dir}"
    chmod 755 -- "${keyrings_dir}"

    scurl -- "${remote_signing_key}" > "${temp_key_file}"

    ## Key verification technique adapted from
    ## https://support.mozilla.org/en-US/kb/install-firefox-linux#w_system-firefox-installation-for-advanced-users
    ## We show the key info from the downloaded key file, then find the 'pub'
    ## section. We discard the 'pub' line itself, and grab the next line
    ## (which is the full key fingerprint). Then we discard leading and
    ## trailing space. This is far more complicated than simply grepping for
    ## the proper fingerprint, but grepping for the fingerpring is unsafe as
    ## an attacker could simply put the proper key fingerprint in their email
    ## address.
    remote_key_fingerprint="$(
      awk -- '/pub/{getline; gsub(/^ +| +$/, ""); print $0}' < <(
        gpg \
          --dry-run \
          --quiet \
          --import \
          --import-options \
          import-show \
          -- \
          "${temp_key_file}"
      )
    )"

    if [ -z "${remote_key_fingerprint}" ]; then
      printf '%s\n' 'ERROR: Could not get fingerprint for signing key!'
      exit 1
    fi

    if [ "${remote_key_fingerprint}" != "${key_fingerprint}" ]; then
      printf '%s\n' 'ERROR: Key fingerprint does not match expected value!'
      exit 1
    fi

    mv -- "${temp_key_file}" "${key_file}"
    safe-rm -rf -- "${temp_dir}"

    printf '%s\n' "${apt_source_line}" | sponge "${apt_source_file}"
    printf '%s\n' "${mozilla_repo_pin}" | sponge "${mozilla_repo_pin_file}"

    apt-get update
    apt-get-noninteractive -y install firefox
    ;;
  remove)
    apt-get-noninteractive -y remove firefox
    ;;
  purge)
    apt-get-noninteractive -y purge firefox
    ;;
  status)
    if pkg_installed firefox; then
      firefox_info_str="$(dpkg-query -s firefox)"
      if [[ "${firefox_info_str}" \
        =~ "${mozilla_maintainer_line}" ]]; then
        exit 0
      fi
    fi
    exit 1
    ;;
  *)
    printf '%s\n' "ERROR: Invalid mode '${modify_mode}'."
    exit 1
esac
