#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

cp --verbose -- /usr/share/browser-choice/keys/mullvad-keyring.asc /etc/apt/keyrings/
cp --verbose -- /usr/share/browser-choice/repo-defs/mullvad.sources /etc/apt/sources.list.d/

apt-get-noninteractive update

apt-get-noninteractive --no-install-recommends --yes install mullvad-browser
