#!/bin/bash

## Copyright (C) 2025 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

set -x
set -e

apt-get-noninteractive update

apt-get-noninteractive --no-install-recommends --yes install tb-updater tb-starter

kernel_cmdline=""
if [ -r '/proc/cmdline' ]; then
  kernel_cmdline="$(cat /proc/cmdline)"
elif [ -r '/proc/1/cmdline' ]; then
  kernel_cmdline="$(cat /proc/1/cmdline)"
fi

if [[ "${kernel_cmdline}" =~ 'boot-role=sysmaint' ]]; then
  printf '%s\n' "$0: INFO: Done installing tb-updater and tb-starter. Reboot into 'PERSISTENT Mode | USER Session', then launch 'Tor Browser (AnonDist)' from the application menu to download and run Tor Browser."
else
  printf '%s\n' "$0: INFO: Done installing tb-updater and tb-starter. Launch 'Tor Browser (AnonDist)' from the application menu to download and run Tor Browser."
fi
