


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChooseInstallationPage(object):
    def setupUi(self, ChooseInstallationPage):
        ChooseInstallationPage.setObjectName("ChooseInstallationPage")
        ChooseInstallationPage.resize(542, 341)
        self.pageLayout = QtWidgets.QVBoxLayout(ChooseInstallationPage)
        self.pageLayout.setObjectName("pageLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(ChooseInstallationPage)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pageLayout.addLayout(self.horizontalLayout)
        self.appNameChoiceLabel = QtWidgets.QLabel(ChooseInstallationPage)
        self.appNameChoiceLabel.setObjectName("appNameChoiceLabel")
        self.pageLayout.addWidget(self.appNameChoiceLabel)
        self.packageChooserWidget = QtWidgets.QWidget(ChooseInstallationPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.packageChooserWidget.sizePolicy().hasHeightForWidth())
        self.packageChooserWidget.setSizePolicy(sizePolicy)
        self.packageChooserWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.packageChooserWidget.setObjectName("packageChooserWidget")
        self.pageLayout.addWidget(self.packageChooserWidget)
        self.label_3 = QtWidgets.QLabel(ChooseInstallationPage)
        self.label_3.setObjectName("label_3")
        self.pageLayout.addWidget(self.label_3)
        self.installRadioButton = QtWidgets.QRadioButton(ChooseInstallationPage)
        self.installRadioButton.setObjectName("installRadioButton")
        self.pageLayout.addWidget(self.installRadioButton)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(25, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.noUpdateCheckbox = QtWidgets.QCheckBox(ChooseInstallationPage)
        self.noUpdateCheckbox.setObjectName("noUpdateCheckbox")
        self.horizontalLayout_3.addWidget(self.noUpdateCheckbox)
        self.pageLayout.addLayout(self.horizontalLayout_3)
        self.removeRadioButton = QtWidgets.QRadioButton(ChooseInstallationPage)
        self.removeRadioButton.setObjectName("removeRadioButton")
        self.pageLayout.addWidget(self.removeRadioButton)
        self.purgeRadioButton = QtWidgets.QRadioButton(ChooseInstallationPage)
        self.purgeRadioButton.setObjectName("purgeRadioButton")
        self.pageLayout.addWidget(self.purgeRadioButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.pageLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backButton = QtWidgets.QPushButton(ChooseInstallationPage)
        icon = QtGui.QIcon.fromTheme("go-previous")
        self.backButton.setIcon(icon)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_2.addWidget(self.backButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.continueButton = QtWidgets.QPushButton(ChooseInstallationPage)
        icon = QtGui.QIcon.fromTheme("go-next")
        self.continueButton.setIcon(icon)
        self.continueButton.setObjectName("continueButton")
        self.horizontalLayout_2.addWidget(self.continueButton)
        self.pageLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ChooseInstallationPage)
        QtCore.QMetaObject.connectSlotsByName(ChooseInstallationPage)

    def retranslateUi(self, ChooseInstallationPage):
        _translate = QtCore.QCoreApplication.translate
        ChooseInstallationPage.setWindowTitle(_translate("ChooseInstallationPage", "Form"))
        self.label.setText(_translate("ChooseInstallationPage", "<span style=\" font-size:20pt; font-weight:600;\">Step 2/4: Choose Installation Options</span>"))
        self.appNameChoiceLabel.setText(_translate("ChooseInstallationPage", "appNameChoiceLabel"))
        self.label_3.setText(_translate("ChooseInstallationPage", "Choose which action to take with the selected package:"))
        self.installRadioButton.setText(_translate("ChooseInstallationPage", "Install"))
        self.noUpdateCheckbox.setText(_translate("ChooseInstallationPage", "Don\'t update software databases before installation"))
        self.removeRadioButton.setText(_translate("ChooseInstallationPage", "Remove"))
        self.purgeRadioButton.setText(_translate("ChooseInstallationPage", "Purge"))
        self.backButton.setText(_translate("ChooseInstallationPage", "Back"))
        self.continueButton.setText(_translate("ChooseInstallationPage", "Continue"))
