


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectApplicationPage(object):
    def setupUi(self, SelectApplicationPage):
        SelectApplicationPage.setObjectName("SelectApplicationPage")
        SelectApplicationPage.resize(659, 645)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SelectApplicationPage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(SelectApplicationPage)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(SelectApplicationPage)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.appChooserTabWidget = QtWidgets.QTabWidget(SelectApplicationPage)
        self.appChooserTabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.appChooserTabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.appChooserTabWidget.setUsesScrollButtons(True)
        self.appChooserTabWidget.setDocumentMode(False)
        self.appChooserTabWidget.setObjectName("appChooserTabWidget")
        self.verticalLayout_2.addWidget(self.appChooserTabWidget)
        self.label_3 = QtWidgets.QLabel(SelectApplicationPage)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.sysmaintWarningLabel = QtWidgets.QLabel(SelectApplicationPage)
        self.sysmaintWarningLabel.setWordWrap(True)
        self.sysmaintWarningLabel.setObjectName("sysmaintWarningLabel")
        self.verticalLayout_2.addWidget(self.sysmaintWarningLabel)
        self.appvmNoticeLabel = QtWidgets.QLabel(SelectApplicationPage)
        self.appvmNoticeLabel.setWordWrap(True)
        self.appvmNoticeLabel.setObjectName("appvmNoticeLabel")
        self.verticalLayout_2.addWidget(self.appvmNoticeLabel)
        self.templatevmNoticeLabel = QtWidgets.QLabel(SelectApplicationPage)
        self.templatevmNoticeLabel.setWordWrap(True)
        self.templatevmNoticeLabel.setObjectName("templatevmNoticeLabel")
        self.verticalLayout_2.addWidget(self.templatevmNoticeLabel)
        self.standalonevmNoticeLabel = QtWidgets.QLabel(SelectApplicationPage)
        self.standalonevmNoticeLabel.setWordWrap(True)
        self.standalonevmNoticeLabel.setObjectName("standalonevmNoticeLabel")
        self.verticalLayout_2.addWidget(self.standalonevmNoticeLabel)
        self.fossNoticeLabel = QtWidgets.QLabel(SelectApplicationPage)
        self.fossNoticeLabel.setWordWrap(True)
        self.fossNoticeLabel.setObjectName("fossNoticeLabel")
        self.verticalLayout_2.addWidget(self.fossNoticeLabel)
        self.nonFossWarningLabel = QtWidgets.QLabel(SelectApplicationPage)
        self.nonFossWarningLabel.setWordWrap(True)
        self.nonFossWarningLabel.setObjectName("nonFossWarningLabel")
        self.verticalLayout_2.addWidget(self.nonFossWarningLabel)
        self.label_6 = QtWidgets.QLabel(SelectApplicationPage)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cancelButton = QtWidgets.QPushButton(SelectApplicationPage)
        icon = QtGui.QIcon.fromTheme("dialog-cancel")
        self.cancelButton.setIcon(icon)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.continueButton = QtWidgets.QPushButton(SelectApplicationPage)
        icon = QtGui.QIcon.fromTheme("go-next")
        self.continueButton.setIcon(icon)
        self.continueButton.setObjectName("continueButton")
        self.horizontalLayout_2.addWidget(self.continueButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(SelectApplicationPage)
        self.appChooserTabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(SelectApplicationPage)

    def retranslateUi(self, SelectApplicationPage):
        _translate = QtCore.QCoreApplication.translate
        SelectApplicationPage.setWindowTitle(_translate("SelectApplicationPage", "Form"))
        self.label.setText(_translate("SelectApplicationPage", "<span style=\" font-size:20pt; font-weight:600;\">Step 1/4: Select Application</span>"))
        self.label_2.setText(_translate("SelectApplicationPage", "Select the application to install or remove."))
        self.label_3.setText(_translate("SelectApplicationPage", "This tool is provided solely for convenience. Users are free to use any applications they choose, installed with or without the help of this tool."))
        self.sysmaintWarningLabel.setText(_translate("SelectApplicationPage", "user-sysmaint-split is installed, and you are currently booted into a user session. You can view applications, but cannot install them. To install applications, please reboot into a sysmaint session. See <a href=\"https://www.kicksecure.com/wiki/Sysmaint\">Sysmaint</a> for more information."))
        self.appvmNoticeLabel.setText(_translate("SelectApplicationPage", "You are currently running Application Chooser inside a Qubes OS app qube. You can view and install applications, but they will be erased after a reboot. This is because most system files in app qubes are reset upon reboot. See <a href=\"https://www.qubes-os.org/doc/templates/\">Qubes Templates</a> for more information."))
        self.templatevmNoticeLabel.setText(_translate("SelectApplicationPage", "You are currently running Application Chooser inside a Qubes OS template qube. Applications installed into this template will be made available in all app qubes based on this template. See <a href=\"https://www.qubes-os.org/doc/templates/\">Qubes Templates</a> for more information."))
        self.standalonevmNoticeLabel.setText(_translate("SelectApplicationPage", "You are current running Application Chooser inside a Qubes OS standalone qube. Applications installed into this qube will only be available within this qube. See <a href=\"https://www.qubes-os.org/doc/templates/\">Qubes Templates</a> for more information."))
        self.fossNoticeLabel.setText(_translate("SelectApplicationPage", "All applications displayed by this tool are open-source software. For more information on the inclusion criteria for applications listed above, see <a href=\"https://www.kicksecure.com/wiki/Dev/browser-choice#criteria_for_inclusion_into_browser_choice\">Criteria for inclusion into browser-choice</a>."))
        self.nonFossWarningLabel.setText(_translate("SelectApplicationPage", "Unofficial plugins for Application Chooser have been installed. The applications above may not be open-source or may be otherwise non-compliant with the inclusion criteria listed in <a href=\"https://www.kicksecure.com/wiki/Dev/browser-choice#criteria_for_inclusion_into_browser_choice\">Criteria for inclusion into browser-choice</a>. Proceed with caution."))
        self.label_6.setText(_translate("SelectApplicationPage", "For more information about this tool, see <a href=\"https://www.kicksecure.com/wiki/Dev/browser-choice\">Dev/browser-choice</a>."))
        self.cancelButton.setText(_translate("SelectApplicationPage", "Cancel"))
        self.continueButton.setText(_translate("SelectApplicationPage", "Continue"))
